name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: nguyenvanuyn96/str-find-and-replace-action@master
        with:
          find: "hello"
          replace: "world"
