name: My Workflow
on: [workflow_dispatch]
jobs:
  build:
  runs-on: "ubuntu-18.04"
  steps:
    - uses: actions/checkout@v2
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with: 
        find: "hello"
        replace: "world"
